### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dolphinsmalltalk/DolphinVM#1]
I would like to point out that identifiers like "[`_IST_INTERPRT_H_`](https://github.com/objectarts/DolphinVM/blob/71c990f653708534be69857cf8a9e38f3af63488/Interprt.h#L11)" and "[`__VMDLL_H_`](https://github.com/objectarts/DolphinVM/blob/71c990f653708534be69857cf8a9e38f3af63488/VMDLL.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by blairmcg** [comment]
No. This reflects the stylistic convention used at the time and it hasn't caused an problems in the past 20 years that the code has existed, so is not a priority to fix.

**Comment by elfring** [comment]
Would you like to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

Will it be better to keep this issue open until all affected implementation details will be fixed?

**Comment by blairmcg** [comment]
You are overstating the severity of the issue. The ability to build the s/w depends on the identifies not clashing with those that might be used in standard libraries, not the behaviour of the s/w itself. As the standard states this is a low severity issue that is unlikely to be a problem. In fact the chances of a name clash are exceedingly low, and as I said this has not been a problem in the past two decades. Personally I don't find it to be a productive exercise to retrospectively apply low-priority standards to old code that is not exhibiting the potential issue identified by the new standard. If you do, then by all means submit a PR.

**Comment by elfring** [comment]
Would you like to reconsider your usage of reserved identifiers once more?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

**Comment by objectarts** [comment]
@elfring, I'm was wondering why you are so concerned with minutae when there are much more important things like #22 to consider. But then I see from [here](https://github.com/elfring) you are a bit of a serial offender.

**Comment by elfring** [comment]
I just dare to gather a bit more attention for issues which might no be so popular occasionally. Some developers improved their software according to my bug reports already.

**Comment by objectarts** [comment]
Further research reveal you to be a serial troll (if not an automaton) whose actions really only result in the further warming of the atmosphere and speed the ever increasing entropy of the entire universe. From your profile you have wasted the time of countless people (and more importantly, myself) so I'm following the course of several others and applying a block.

**Comment by elfring** [comment]
Can any other information sources change your opinion eventually?
