### ISSUE TITLE
ProcessTest>>#testSchedulerTermination

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#12]
In the Debug configuration this hits an assert in Process.cpp:

1106: `HARDASSERT(proc->Next()->isNil());`
633: `HARDASSERT(newActive->Next()->isNil());`
680: `HARDASSERT(newActive->Next()->isNil());`
591: `HARDASSERT(actualActiveProcess()->Next()->isNil());`
861: `HARDASSERT(process->Next()->isNil());`
1058: `HARDASSERT(lastLink->Next()->isNil());`

I haven't investigated at all but given the name of the test (#testSchedulerTermination) it seems not very surprising that there is a Process instance hanging around.

**Comment by blairmcg** [comment]
Same issue as #72. No longer repro's with fix for that.
