### ISSUE TITLE
Enhance VM build intructions

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/DolphinVM#129]
In a clean W10 system and following the readme.md instructions, after installed VS 2015 Community edition I was unable to build DolphinVM.

That was because (at least my download) VS 2015 ships the 8.1 SDK and the solution targets 10.1
I've to manually download the [10.1 SDK installer](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk)

Additionally I've to add the 8.1 SDK midl compiler to the path:
`C:\Program Files (x86)\Windows Kits\8.1\bin\x86`

I could provide a PR for this.

**Comment by blairmcg** [comment]
A better option is to install the SDK from the VS2015 installer:
![image](https://cloud.githubusercontent.com/assets/15128107/25641180/a7bfac3a-2f8a-11e7-80f4-df4bc8132b30.png)
The instructions could usefully mention the need to select this option.
I don't recognise the need to amend the path to find the MIDL compiler as I've never had to do that. You want to use the 10 version anyway.

**Comment by fxgallego** [comment]
I just checked the installer I've used and, yes the option is there, slightly deep for my preference. Anyway I think it's better to mention the requirement. As for the path to the MIDL compiler sure that was needed because the installation of the SDK using another installer.

**Comment by blairmcg** [comment]
The VM can now be built with VS2017 by choosing the Desktop development with C++ workload. There is no need to build the solution twice - if there were the AppVeyor build would not be working. I'm not sure why you have to do that.
