### ISSUE TITLE
Runtime hangs on Windows 7 starting with 7.0.42

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#135]
Using Windows 10 (my development environment) I've long been able to generate an executable that runs on Windows 7 (a customer's runtime environment). To exclude my code as an issue, I've deployed a Notepad.exe and tried it. With VM 7.0.41 (12-March-2017) and Dolphin commit 2b8d8504d5ad09a5ffd8412f0ce0d3d202d88c96 from 13-July-2017, everything works fine. With VM 7.0.42 (14-July-2017) and Dolphin commit cc0b517bfe297c33a2d72e7634c2d57321a0baf1 from 14-July-2017, we get a hang and the application is non-responsive and must be terminated from the Task Manager. Prior to terminating I was able to get a Windows dump file (36MB) and open it with VS2015. It appears to be in Interpreter::primitiveMillisecondClockValue(). I'm not sure if that helps. Is there a way to force a Smalltalk stack?

![screen shot 2017-07-19 at 1 12 28 pm](https://user-images.githubusercontent.com/1577872/28387589-8a59f7fe-6c84-11e7-8bd0-840326be3da5.png)

I see a comment in environ.h on line 25 that we are supporting Windows 8?

**Comment by andygraham** [comment]
This must be because of the change made to the VM in 7.0.42 to support pen and touch input. I now remember that Andy Bower and I found that it hung Windows 7 when I raised the pen and touch issue under Windows 8 mearly four years ago.
[That thread is here](http://compgroups.net/comp.lang.smalltalk.dolphin/dolphin-x6.1-and-windows-8-tpuch/2518757)

**Comment by andygraham** [comment]
Sorry, I got confused. I'm getting old and don't really understand how GitHub works :(

I didn't read your commit carefully and now see that it WAS to the image. Blair made a corresponding change to the VM to check the same flags for the occasions when the VM needs to signal the semaphore so either that needs a similar check or it is intriguing that the change hangs the in the image but not in the VM.

**Comment by jgfoster** [comment]
I entered this issue against the VM when I saw that the minimum OS level was changed here. The fact that I'm able to get beyond the existing issue with an image fix solves my immediate problem but if we can get pen and touch input to work in Windows 8 without dropping support for Windows 7, that would be very nice. Also, I'm not sure that my image-based "solution" is any more than a "hack."

**Comment by blairmcg** [comment]
See 3ca07425a749279ed77f8b80a0c48ffeb38f461e
