### ISSUE TITLE
VM Debug build fails with MIDL error

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/DolphinVM#151]
(Hope this isn't my beginners error :)
When building in "VM Debug" mode, this error is given:
    "Error MIDL2338 switches are contradictory -no_robust vs. -target"
This error occurs twice, for the projects "VM" and "DolphinLib".
.
Inspection of the MIDL settings for these projects shows 
that the debug config has "Minimum Target System" set to "NT60", 
whereas the release config does not have this setting.
Removing it succescully builds the debug config.
I have not tested the resulting VM...

**Comment by blairmcg** [comment]
This started happening with a recent patch to VS2017. It started defaulting the MinimumTargetSystem so this has to be cleared out. The change you made is correct. I fixed it for the release build some time ago, but forgot to apply it to all configurations.

**Comment by FunctionPoint** [comment]
Okay, thank. Could you possibly take it aloung with some next commit? I don't feel comfortable enough yet with Git. It's my new years resolition, though. And to contribute something :).

**Comment by blairmcg** [comment]
Sure, I extracted the commit I had for this in some work in progress and pushed it. I'll merge it if the build passes.

**Comment by FunctionPoint** [comment]
Great, tnx!
