### ISSUE TITLE
VM project fails to load in VStudio solution

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/DolphinVM#162]
When I do a fresh clone of the VM, the solution fails to load the VM (sub)project.
Reloading it manually gives this error:
"DolphinVM\dll.vcxproj : error  : Cannot load project with duplicated project items: rc_vm.h is included as 'ClInclude' and as 'ClInclude' item types"
.
Possibly related the file VMLib.vcxitems.filters, which gives the following diff in GitDesktop:
(note hardcoded pathname)
"-    \<ClCompile Include="D:\dev\blairmcg\Dolphin\Core\DolphinVM\VMLib\IntPrim.cpp"\>
"-      \<Filter\>Primitives\</Filter\>
"-    \</ClCompile\>
"+    \<ClCompile Include="$(MSBuildThisFileDirectory)IntPrim.cpp" /\>
.
Additionally  I've updated to the current VStudio: 15.6.2.
This gave some new warning grief, but not sure if it was on the original or my changed stuff.

**Comment by FunctionPoint** [comment]
Hi @blairmcg , could you possibly take a quick look at this?
Do you get the same error?
I fixed it locally my removing the file rc_vm.h item group entry from the VM(lib) project file with a text editor.

**Comment by blairmcg** [comment]
This is fixed in both master and the 7.1 branches.

**Comment by FunctionPoint** [comment]
Thanks!
