### ISSUE TITLE
Use C99 fixed-width C integer types

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#163]
The C99 standard includes definitions of several new integer types to enhance the portability of programs (per [Wikipedia](https://en.wikipedia.org/wiki/C_data_types#Fixed-width_integer_types)). I'm looking for some simple tasks where students could make a contribution. This seemed like a reasonable one so I'll create an issue to track it.

**Comment by blairmcg** [comment]
This issue was moved to dolphinsmalltalk/Dolphin#535
