### ISSUE TITLE
Compiler::GenPopAndStoreTemp() triggers assert in Debug

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#19]
With PR #18 we now see an intermittent assert in `Compiler::GenInstructionExtended()`. The problem is that `GenData()` (`compiler.cpp:533`) accepts a `BYTE` while `m_pCurrentScope->GetDepth()` (line 1195) returns an int that occasionally has the value out of range (256 in a couple cases). I've seen this with the following:
`CompilerErrorTest debug: #testErrorsBlockNestingTooDeep`
Interestingly, if I continue from the assert then the test eventually finishes and passes.

**Comment by blairmcg** [comment]
This definitely looks like a compiler bug (an off by one error).

**Comment by blairmcg** [comment]
Fixed with commit 4d2c8a9
