### ISSUE TITLE
Select line-ending convention for DolphinVM text files

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#23]
Further comments on the extensive diffs on my recent commit to #21: 

From a Windows machine I tried downloading the zip from GitHub, unzipped it, and then opened several files in Notepad++. In each case it appears that the files were originally committed using a Unix line ending convention (LF rather than CRLF). I'm happy to follow that convention (it works well for my Git tools) but I understood from earlier discussions that there was a preference for using CRLF in all text files (which is why I added the `.gitattribute` line that created the extra edits and made the diffs essentially worthless). 

Given that the original files seem to be Unix-based (perhaps the original GitHub push was from a Mac), it seems to me that the best thing would be to change `.gitattributes` to cause all text files to stay in Unix mode to reduce the diff noise. Thoughts?

**Comment by objectarts** [comment]
@jgfoster we certainly don't want to end up with Unix line endings in the code by default. It is very possible that I may have made the original commit from a Mac (but I have learnt my lesson now and only use Windows). I'll look into how to change these with the least possible problems.

One thing I don't understand is why Blair's changes are coming through with correct DIFFs when he is working solely on Windows. Are you still downloading files via Git on the Mac - it might that causing the issue?

**Comment by jgfoster** [comment]
Many of my changes are also coming through with correct DIFFs so it isn't a general problem on my end. Without knowing more I suspect that Blair did the download after I added the .gitattribute flag to convert things to CRLF. I believe that there are some tricks I may be able to do to get my previously-downloaded files to convert before they are edited.

**Comment by blairmcg** [comment]
@jgfoster, as we have your gitattributes change now, are we done with this one?
I did still see a few CR/LF issues when resolving merge conflicts (I used VS2015 to resolve the merge, and it prompted to correct a couple of files that had mixed line endings), but subsequent to that I'm not seeing issues with diffs.

**Comment by jgfoster** [comment]
Yes, I'll close this since we have an agreement on what should be done and it seems to be working as we want.
