### ISSUE TITLE
Get DolphinVM to build for Debug configuration

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/DolphinVM#4]

**Comment by fxgallego** [comment]
There is a config in ToGoLib [project](https://github.com/dolphinsmalltalk/DolphinVM/blob/master/ToGoLib/ToGoLib.vcxproj) that requires the file "..\Boot\vmref.cpp" in lines 90..92. The file can't be found in the project.
Maybe this file was accidentally not commited.

**Comment by objectarts** [comment]
@fxgallego, I think it is unnecessary and can be removed.

**Comment by jgfoster** [comment]
Is this ready to be closed? The Debug configuration builds and we have separate issues for failing tests.

**Comment by objectarts** [comment]
Yes, I think we can close this now.
