### ISSUE TITLE
Build error with 3dd0ccb

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#48]
Severity	Code	Description	Project	File	Line	Suppression State

Error	C2065	'IsWindowsThresholdOrGreater': undeclared identifier	VMLib	M:\Documents\Dolphin\Core\DolphinVM\exports.cpp	145	
Error	C2065	'IsWindows10OrGreater': undeclared identifier	VMLib	M:\Documents\Dolphin\Core\DolphinVM\exports.cpp	146

**Comment by blairmcg** [comment]
@jgfoster, the AppVeyor build succeeded. Are you on VS2015 update 1? These functions are (or should be) declared in the VersionHelpers.h header file. It sounds like you have a Windows 8.1 version of the platform SDK.

**Comment by jgfoster** [comment]
Yes, I'm on VS2015 update 1. Under Properties the target platform version is 8.1. What should it be?

**Comment by blairmcg** [comment]
Doesn't sound right. The TargetPlatformVersion in the projects is 10.0.10240.0, and has been since the switch to VS2015.

**Comment by jgfoster** [comment]
https://www.reddit.com/r/cpp_questions/comments/3q2np6/getting_windows_10_version_iswindows10orgreater/ seems to describe my situation and by following the instructions there I have a clean build.

**Comment by jgfoster** [comment]
@blairmcg, so is Windows 10 the minimum required platform for both development and runtime? I can see moving away from Windows XP but is it reasonable to say Dolphin-built applications won't run on Windows 7, 8.0, and 8.1?

**Comment by blairmcg** [comment]
No. The main effect of that setting for C++ projects is to change the SDK that is used to import headers from. When Dolphin was built to target Windows 8, it still ran on Windows 7. Targetting Windows 10 makes newer APIs available, but doesn't mean they have to be used, or used in such a way that prevents running downstream by degrading gracefully. The VM itself calls very few Windows APIs, so most of the versioning decisions are made in the image, where one can use polymorphism to good effect to accommodate different platforms. We decided to leave the WinXP support in the image BTW, even though it is unwise to use XP.
