### ISSUE TITLE
Dolphin Compiler should be statically linked in the VM DLL

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/DolphinVM#5]
The Dolphin compiler currently resides in **DolphinCR7.dll** which means that it must be present in the same folder as any deployed application that makes use of it (or it must be registered as a COM component so it can be global located). It would be safer and more straightforward if the compiler became a part of the VM.

**Comment by blairmcg** [comment]
As the compiler will be replaced, it doesn't seem worthwhile making this change now.
