### ISSUE TITLE
Compiler generates inefficient code for #ifNotNil: with zero arg block

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/DolphinVM#60]
Given an #ifNotNil: statement the compiler may generate inefficient code if the block argument itself has no arguments, e.g. from SmalltalkParser>>step

`currentToken ifNotNil: [currentToken comments ifNotNil: [:c | comments addAll: c]].`

produces

```
	1	Push Inst Var[1]: currentToken
	2	Dup
	3	Jump If Nil +10 to 15
	5	Pop
	6	Push Inst Var[1]: currentToken
	7	Send[0]: #comments with 0 args
	8	Dup
	9	Jump If Nil +4 to 15
	11	Pop Temp[0]
	12	Push Inst Var[7]: comments
	13	Push Temp[0]
	14	Send[1]: #addAll: with 1 args
	15	Pop
	16	Push Inst Var[2]: nextToken
...
```
Here the compiler generates a Dup at 2 expecting to want to test for nil, then store to a temp to be used by the block. However the block doesn't use the temp, so it is just Pop'd at 5. It also has to be Pop'd at 15 (the target of the conditional jump when nil). The Dup and Pops bytecodes are not required and could be optimized away.

**Comment by frank-lesser** [comment]
Hi Blair, would be nice to have some private email contact, frank-lesser@lesser-software.com
