### ISSUE TITLE
Compiler temps map has wrong scope depth for full blocks nested in non-full blocks

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/DolphinVM#83]
When calculating the "outer depth" for reference to locals declared in enclosing scopes the compiler assumes that each intervening block always has a context, but in fact this is not necessarily the case. Only full blocks will have their own contexts - blocks that don't declare any variables assigned to in nested blocks do not need a context. The compiler generates the correct instructions to take account of this, but fails to use the correct calculation when building the map of information about the temps that are in scope for ranges of instructions. This causes problems for the Debugger which relies on the temp map to build and display information about the variables that are in scope at the current program location.

**Comment by blairmcg** [comment]
On testing I am finding other cases that are incorrect such as shared temps declared in optimized blocks that are promoted to the nearest enclosing non-optimized scope.

**Comment by fxgallego** [comment]
Hi Blair, sorry, but I've noticed you are working on the compiler. I suspect that the compiler is not thread safe. Please, let me know if you think I'm wrong in order to develop a test case.

**Comment by blairmcg** [comment]
I am fixing a bug in it, yes. I'm also working on replacing it with an implementation in Smalltalk, but progress on that has been slow.
You are right, the compiler is not thread safe. That was never a design objective.

**Comment by fxgallego** [comment]
Blair, thanks for your answer and for your work in the compiler. I've realized about the problem working in an "Web MVC" like framework, sending lots of #evaluate: from different threads. I though that something where wrong but now that you confirm this we will be more conservative using the compiler.
